# Generated by Django 3.0.5 on 2020-06-15 19:14

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import hopskotch_auth.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SCRAMCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', django_enumfield.db.fields.EnumField(editable=False, enum=hopskotch_auth.models.SCRAMAlgorithm)),
                ('salt', models.BinaryField(max_length=128)),
                ('server_key', models.BinaryField(max_length=256)),
                ('stored_key', models.BinaryField(max_length=256)),
                ('string_encoding', models.TextField(editable=False)),
                ('iterations', models.IntegerField(editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.KafkaIdentity')),
            ],
        ),
    ]
