# Generated by Django 3.0.5 on 2020-06-25 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hopskotch_auth', '0002_auto_20200625_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafkaidentity',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='kafkaidentity',
            name='username',
        ),
        migrations.RemoveField(
            model_name='scramcredentials',
            name='user',
        ),
        migrations.AddField(
            model_name='scramcredentials',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scramcredentials',
            name='username',
            field=models.CharField(default='unknown', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
