# Generated by Django 3.0.5 on 2020-06-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0003_auto_20200625_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KafkaIdentity',
        ),
    ]
