# Generated by Django 3.0.7 on 2021-02-08 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import hopskotch_auth.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hopskotch_auth', '0004_delete_kafkaidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='scramcredentials',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KafkaTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=249)),
                ('publicly_readable', models.BooleanField(default=False)),
                ('owning_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enumfield.db.fields.EnumField(enum=hopskotch_auth.models.MembershipStatus)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupKafkaPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', django_enumfield.db.fields.EnumField(editable=False, enum=hopskotch_auth.models.KafkaOperation)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.Group')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.KafkaTopic')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='hopskotch_auth.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CredentialKafkaPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', django_enumfield.db.fields.EnumField(editable=False, enum=hopskotch_auth.models.KafkaOperation)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.GroupKafkaPermission')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.SCRAMCredentials')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.KafkaTopic')),
            ],
        ),
    ]
