# Generated by Django 3.0.7 on 2021-03-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0005_add_authz'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='kafkatopic',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='scramcredentials',
            name='description',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
