# Generated by Django 3.0.7 on 2021-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0005_add_authz'),
    ]

    operations = [
        migrations.AddField(
            model_name='scramcredentials',
            name='nickname',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
