# Generated by Django 3.0.12 on 2022-05-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0006_add_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCRAMExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_nonce', models.CharField(editable=False, max_length=128, unique=True)),
                ('s_nonce_len', models.IntegerField(editable=False)),
                ('client_first', models.CharField(max_length=512)),
                ('cred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.SCRAMCredentials')),
            ],
        ),
    ]
