# Generated by Django 3.2.13 on 2022-07-21 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0008_auto_20220519_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='scramexchange',
            name='began',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
