# Generated by Django 3.2.17 on 2023-07-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0011_scram_exchange_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauthtoken',
            name='derived_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopskotch_auth.scramcredentials'),
        ),
    ]
