# Generated by Django 4.2.25 on 2026-03-04 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0013_mailinglistmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafkatopic',
            name='index_archived_text',
            field=models.BooleanField(default=True),
        ),
    ]
