# Generated by Django 4.2.25 on 2026-09-24 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0014_add_index_archived_text_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentMessages',
            fields=[
                ('topic', models.TextField(primary_key=True, serialize=False)),
                ('e_timestamp', models.BigIntegerField()),
                ('l_timestamp', models.BigIntegerField()),
                ('n_messages', models.BigIntegerField()),
            ],
            options={
                'db_table': 'topics',
                'managed': False,
            },
        ),
    ]
