# Generated by Django 4.2.25 on 2025-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hopskotch_auth",
            "0014_recentmessage_alter_credentialkafkapermission_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField()),
                ("timestamp", models.BigIntegerField()),
            ],
            options={"db_table": "recent_messages", "managed": False,},
        ),
        migrations.DeleteModel(name="RecentMessage",),
    ]
