# Generated by Django 4.2.25 on 2026-09-24 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopskotch_auth', '0015_recentmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONWebKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(editable=False, max_length=128, unique=True)),
                ('private_data', models.BinaryField(max_length=4096)),
                ('not_before', models.BigIntegerField()),
                ('expiration', models.BigIntegerField()),
            ],
        ),
    ]
