name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Run migrations
        run: docker-compose exec django python manage.py migrate
      - name: Run tests
        run: docker-compose exec django python manage.py test
