name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install secrets
        env:
          CILOGON_CLIENT_SECRET: ${{ secrets.CILOGON_CLIENT_SECRET }}
        run: python scripts/setup_ci_secrets.py

      - name: Set up a postgres database
        run: python scripts/create_db.py --with-docker

      - name: Run migrations
        run: python scimma_admin/manage.py migrate --no-input

      - name: Run tests
        run: |
          cd scimma_admin
          python manage.py test --no-input
